### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by WangChing0723**
I finished my code and transformed the data and insert into database, please check it , thanks.

### CODE REVIEW

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
Please revise the following parts:
1. Don't include your db's information in the python script, especially your user & password.
2. Alter your SQL scripts. Use %s instead of f-string.
3. Delete the useless file, such as project.py

**Comment by WangChing0723** [comment]
I finished all parts and I updated it , but I have some questions about 1.  ,please check it.

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
1. Don't put key.py onto GitHub. Otherwise, others can access your resources easily.
2. You still need to change the f-string parts to safer ways of passing data into databases.

**Comment by WangChing0723** [comment]
I finished it, Please check it, thanks.

**Review by chengchiehhung — COMMENTED** [review]
ok

**Review by chengchiehhung — APPROVED** [review]
ok

**Pull request merged**
